name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install -g bats
    - run: bats -v
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
    - run: echo "What time is is?"
  echo-stuff2:
    needs: echo-stuff
    runs-on: ubuntu-latest
    steps:
    - run: date
  echo-stuff3:
    needs: echo-stuff2
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_WORKSPACE  
  example-job:
    runs-on: ubuntu-latest
    env:
      SCRIPT_PATH: ./.github/scripts
    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: ls -la
    - name: run a script
      run: chmod +x ${SCRIPT_PATH}/1.sh
    - run: ${SCRIPT_PATH}/1.sh
      shell: bash     
  echo-aws-cli:
    runs-on: ubuntu-latest
    steps:
    - run: aws --help