# Referenced in the GIA Platform Documentation
# Configure AWS Credentials: https://github.com/aws-actions/configure-aws-credentials#usage

# Work on GitHub?
# yes

# Work with ACT?
# No

# Comments
# ---------
# OIDC requires a trust relationship between GH and AWS, which isn't present when running locally.
# I suspect that ACT would work if creds were stored as GH secrets.
# I'll see as I test other actions.

name: List AWS Buckets
run-name: ${{ github.actor }} is printing bucket names
on: push

jobs:
  list-buckets:
    name: List AWS S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Set Output Params
      id: set-output
      run: |
        # echo "MY_TEST1=$AWS_SESSION_TOKEN" >> $GITHUB_OUTPUT
        echo "MY_TEST2=my_test2" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v3

    # - name: Configure AWS credentials - GitHub
    #   if: ${{ secrets.AWS_SESSION_TOKEN == null }}
    #   uses: aws-actions/configure-aws-credentials@v1-node16
    #   with:
    #     role-to-assume: arn:aws:iam::223356124846:role/bks_brian-sigurdson_gh-practice
    #     aws-region: us-east-1

    # - name: Configure AWS credentials - Local
    #   if: ${{ secrets.AWS_SESSION_TOKEN != null }}
    #   uses: aws-actions/configure-aws-credentials@v1-node16
    #   with:
    #     role-to-assume: arn:aws:iam::223356124846:role/bks_brian-sigurdson_gh-practice
    #     aws-region: us-east-1
    #     web-identity-token-file: ${{ secrets.AWS_SESSION_TOKEN }}

    # - name: List bucket names
    #   run: |
    #     aws s3 ls
      
    - name: Test env params
      run: |
        # echo "MY_TEST1"
        # echo "${{ steps.set-output.outputs.MY_TEST1 }}"
        echo "MY_TEST2"
        echo "${{ steps.set-output.outputs.MY_TEST2 }}"
        echo "act secret"
        echo "${{ secrets.AWS_SESSION_TOKEN }}"        