# Referenced in the GIA Platform Documentation
# Configure AWS Credentials: https://github.com/aws-actions/configure-aws-credentials#usage

# Work on GitHub?
# yes

# Work with ACT?
# No

# Comments
# ---------
# OIDC requires a trust relationship between GH and AWS, which isn't present when running locally.
# I suspect that ACT would work if creds were stored as GH secrets.
# I'll see as I test other actions.

name: List AWS Buckets
run-name: ${{ github.actor }} is printing bucket names
on: push

jobs:
  list-buckets:
    name: List AWS S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Set Output Params
      id: set-output
      run: MY_TEST=$AWS_SESSION_TOKEN

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials from Test account
      if: ${{ env.MY_TEST == null }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::223356124846:role/bks_brian-sigurdson_gh-practice
        aws-region: us-east-1
        # web-identity-token-file: "$AWS_SESSION_TOKEN"

    - name: List bucket names
      run: |
        aws s3 ls
      
    - name: Test env params
      run: |
        echo "testing"
        echo "${{ steps.set-output.outputs.MY_TEST }}"
        echo "testing"