name: Display secrets
run-name: ${{ github.actor }} is running a job
on: push

jobs:
  show-repo-secrets:
    name: List Repo Secrets
    runs-on: ubuntu-latest
    steps:
    - run: echo "DEMO_SECRET (repo): ${{ "secrets.DEMO_SECRET" }}
    - run: echo "REPO_SECRET_001 (repo): ${{ "secrets.REPO_SECRET_001" }}