name: ECR - aws-actions/amazon-ecr-login
run-name: ${{ github.actor }} is pushing to ECR
on: push

# Locally, the env vars will be set to inputted values, but on GH they should be null and 
# (i think) they are set by aws-actions/configure-aws-credentials@v1-node16 during authentication
env:
  SESSION_TYPE: 'not-local'
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  # ECR_REPOSITORY: 'bks/testing'
  # CONTAINER_REGISTRY_HOST: '223356124846.dkr.ecr.us-east-1.amazonaws.com'
  

jobs:
  test-erc:
    name: Test ECR Actions
    runs-on: ubuntu-latest

#################### (below) boiler plate stuff needed for each run ####################
   
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Local - Install dependencies
      if: ${{ env.SESSION_TYPE == 'local' }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install > /dev/null
        apt-get -y install less

    - name: Checkout
      uses: actions/checkout@v3     

    - name: GitHub - Configure AWS credentials
      if: ${{ env.SESSION_TYPE == 'not-local' }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::223356124846:role/bks_brian-sigurdson_gh-practice
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

#################### (above) boiler plate stuff needed for each run ####################

    - name: Run stuff
      run: |   
        ls -la ./aws
        echo $USER
        whoami


    - name: Login to Amazon ECR
      if: ${{ env.SESSION_TYPE == 'not-local' }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      if: ${{ env.SESSION_TYPE == 'not-local' }}
      with:
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: 'bks/testing'
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./docker_stuff/
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # here is where you need to add code to handle working locally with ACT
    # this page has awscli commands:  https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html
    # this may help:  https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/index.html
    # I may need to configure this to avoid storing passwords even on temp instances: 
    # https://docs.docker.com/engine/reference/commandline/login/#credentials-store 
